name:                discord-haskell-voice
version:             2.3.1
description:         Supplementary library to discord-haskell.
                     See the project README on GitHub for more information.
                     <https://github.com/yutotakano/discord-haskell-voice>
synopsis:            Voice support for discord-haskell.
github:              "yutotakano/discord-haskell-voice"
license:             MIT
author:              Yuto Takano
maintainer:          "moa17stock@gmail.com"
copyright:           "2021-2022 Yuto Takano"
category:            Network
extra-source-files:
- README.md
- ChangeLog.md

default-extensions:  OverloadedStrings

flags:
  use-shecretbox:
    description: Use Shecretbox, a Haskell implementation of secretbox encryption, powered using cryptonite. If off, requires libsodium to dynamically link to.
    manual: yes
    default: no

dependencies:
  - base >= 4.7 && < 5
  - conduit >= 1.3.4.2 && <= 1.4.0.0
  - discord-haskell >= 1.12.0 && <= 1.15.3
  - text >= 1.2.4.1 && < 2

library:
  source-dirs: src
  # ghc-options:
  #   - -Werror
  #   - -Wall
  #   - -Wcpp-undef
  #   - -Widentities
  #   - -Wincomplete-record-updates
  #   - -Wincomplete-uni-patterns
  #   - -Wpartial-fields
  #   - -Wredundant-constraints
  #   - -Wmissing-deriving-strategies
  #   - -Wmissing-export-lists
  #   - -Wunused-packages
  #   - -Wno-name-shadowing
  #   - -Wno-type-defaults

  dependencies:
  - aeson >= 1.5 && < 1.6 || >= 2.0 && < 2.2
  - async >= 2.2.3 && < 2.4
  - binary >= 0.8 && < 0.9
  - BoundedChan == 1.0.3.0
  - bytestring >= 0.10.12.0 && < 0.12
  - conduit-extra == 1.3.6
  - microlens >= 0.4.11.2
  - microlens-th >= 0.4.3.10
  - mtl == 2.2.2
  - network >= 3.1.1.1 && < 3.2
  - opus == 0.1.0.0
  - safe-exceptions >= 0.1.7.1 && < 0.1.8
  - stm >= 2.5.0.0 && <= 2.6.0.0
  - time >= 1.9.3 && <= 1.13
  - unliftio >= 0.2.18 && < 0.3
  - websockets >= 0.12.7.2 && < 0.12.8
  - wuss >= 1.1.18 && < 2.1.0.0

  when:
  - condition: flag(use-shecretbox)
    then:
      cpp-options: -DUSE_SHECRETBOX
      dependencies:
      - cryptonite >= 0.29
      - shecretbox == 0.0.1
    else:
      dependencies:
      - saltine >= 0.1.1.1 && < 0.3
  # The exposed-module specifies the exact order the modules will appear in the
  # generated cabal file, and thus on Haddock. The default is alphabetical, but
  # internals should be later.
  exposed-modules:
  - Discord.Voice
  - Discord.Voice.Conduit
  - Discord.Internal.Types.VoiceCommon
  - Discord.Internal.Types.VoiceUDP
  - Discord.Internal.Types.VoiceWebsocket
  - Discord.Internal.Voice
  - Discord.Internal.Voice.CommonUtils
  - Discord.Internal.Voice.UDPLoop
  - Discord.Internal.Voice.WebsocketLoop

executables:
  join-all-on-start:
    main:           examples/JoinAllVC.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discord-haskell-voice
    - safe-exceptions >= 0.1.7.1 && < 0.1.8

  basic-music-bot:
    main:           examples/BasicMusicBot.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discord-haskell-voice
    - optparse-applicative >= 0.15.1.0 && < 0.18
    - stm >= 2.5.0.0 && < 2.5.1
    - stm-containers == 1.2
    - unliftio >= 0.2.18 && < 0.3
